name = LAADP Site
description = Site layout for LAADP.
preview = preview.png
template = site-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer_first]   = Footer First
regions[footer_second]  = Footer Second

; Stylesheets
stylesheets[all][] = css/layouts/site/site.layout.css
